env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-console: off
  no-underscore-dangle: off
  semi:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
